### PR TITLE
fix: add attachments correctly

### LINKED ISSUE #21: Should be able to upload all attachments via BugSplatCrashHandler
When using BugSplatCrashHandler as a BsSndRpt replacement I want to upload all my attachments so they are associated with the crash report.

[View related Userfeed post](https://www.userfeed.io/permalink/orgs/defefc46-34fc-4e14-b4aa-10759ccd3193/posts/b344ca3e-1aa9-4a7d-aad9-963a99ecd4ba)

### PR DESCRIPTION
**Pull request by bobbyg603**
### Description

Fixes #21 

### Checklist

- [x] Tested manually
- [x] Unit tests pass with no errors or warnings
- [x] Documentation updated (if applicable)
- [x] Reviewed by at least 1 other contributor

### CODE REVIEW

**Review by daveplunkett — APPROVED** [review]

File: Program.cs [hunk 1]
```diff
@@ -41,6 +41,11 @@ public class Options
 
         static void RunOptions(Options opts)
         {
+            while (!Debugger.IsAttached)
+            {
+                System.Threading.Thread.Sleep(100);
+            }
+
```
Comment (bobbyg603) [inline Program.cs:48]:
```suggestion
```
